parameters:
  - name: WebAppKind
    displayName: app Type
    type: string
    default: webAppLinux

variables:
  - name: ConnectedServiceName
    value: RDSNODEVSERVERCON
  
  - name: WebAppName
    value: nodeExpressDemonoDev


trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.DefaultWorkingDirectory)'


- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service to Slot'
  inputs:
    azureSubscription: 'RDSNODEVSERVERCON'
    appType: 'webAppLinux'
    WebAppName: 'nodeExpressDemonoDev-dev'
    packageForLinux: $(System.DefaultWorkingDirectory)/**/*.zip
    
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'RDSNODEVSERVERCON'
    Action: 'Swap Slots'
    WebAppName: 'nodeExpressDemonoDev'
    ResourceGroupName: 'rds-operational-no-dev'
    SourceSlot: 'dev'

