parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: Release
    values:
      - Release
      - Debug

  - name: publishArtifacts
    displayName: Publish artifacts
    type: boolean
    default: false

  - name: applicationName
    displayName: Name of the function app
    type: string

  - name: jobSuffix
    displayName: Job suffix
    type: string

jobs:
  - job: Build_${{parameters.jobSuffix}}
    displayName: 'Build ${{parameters.jobSuffix}}'
    workspace:
      clean: resources
    
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'

    - script: |
        npm test
      displayName: 'npm test'

    - task: ArchiveFiles@2
      condition:  succeeded()
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false

  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: ${{parameters.applicationName}}
        publishLocation: 'Container'

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: ${{parameters.applicationName}}        
        downloadPath: '$(System.DefaultWorkingDirectory)'